name: Blog Workflow

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: macOS-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
      - uses: actions/checkout@v1
      - name: Initial Environment
        env:
          SSH_KEY: ${{secrets.SSH_KEY}}
          SSH_USER: ${{secrets.SSH_USER}}
          SSH_IP: ${{secrets.SSH_IP}}
          SSH_PORT: ${{secrets.SSH_PORT}}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          printf "Host blog\n    HostName $SSH_IP\n    User $SSH_USER\n    Port $SSH_PORT" > ~/.ssh/config
          { ssh-keyscan -p $SSH_PORT $SSH_IP 2> /dev/null; } >> ~/.ssh/known_hosts

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: |
          npm i yarn -g
          yarn global add gulp
          yarn install && gulp
          rsync -az -v --delete public/* blog:/data/www/blog/
